# Generated by Django 6.0.2 on 2026-03-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='completed',
        ),
        migrations.AddField(
            model_name='progress',
            name='actual_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='completion_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='progress',
            name='planned_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='planned_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='status',
            field=models.CharField(default='planned', max_length=32),
        ),
        migrations.AlterField(
            model_name='progress',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
