# Generated by Django 6.0.2 on 2026-03-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0002_remove_progress_completed_progress_actual_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='actual_minutes',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='status',
        ),
        migrations.AddField(
            model_name='progress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progress',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='planned_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='planned_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
